#!/bin/sh

case $# in
1) ;;
*) echo "Usage: $0 { SERVER | @ENV }"; exit 0;;
esac

# project revision to deploy
r=$(cd $(dirname $0)/.. && grep '<global.version>' pom.xml|awk 'BEGIN{FS="[<>]"}{print $3}')
g=$(cd $(dirname $0)/.. && grep '<groupId>' pom.xml|head -1|awk 'BEGIN{FS="[<>]"}{print $3}'|sed 's/\./\//g')

echo $r
echo $g

ctrl() {
    if m=`expr "$2" : '\(.*[^.0-9]\)[0-9]*\..*'` > /dev/null
    then
        echo "Deploying '$m' to server '$2' ..."
        ssh root@$2 /bin/rm -rf '${CATALINA_HOME:-/usr/tomcat}/webapps/'$m
        ssh root@$2 /bin/mkdir -p /root/deployment
        echo "put ${M2_REPO:-$HOME/.m2/repository}/$g/$m/$r/$m-$r.war deployment" | sftp -oBatchMode=yes -b - root@$2 > /dev/null
        ssh root@$2 /bin/ln -sf /root/deployment/$m-$r.war '${CATALINA_HOME:-/usr/tomcat}/webapps/'$m.war
    else
        echo "Unknown server: $2"
    fi
}

. $(dirname $0)/apply
apply "" "$1" +

