#!/bin/sh

case $# in
1) ;;
*) echo "Usage: $0 { SERVER | @ENV }"; exit 0;;
esac

# project revision to deploy
CTL=$(dirname $(readlink -f $0))
REV=$(grep '<version>' pom.xml|head -1|awk 'BEGIN{FS="[<>]"}{print $3}')

echo $CTL
echo $REV

ctrl() { # argument host env
    local m
    if m=`expr "$2" : '\(.*[^.0-9]\)[0-9]*\..*'` > /dev/null
    then
        local p="$m"
        while [ "$p" -a ! \( -f "deploys/$p/pom.xml" \) ]; do
            echo "directory 'deploys/$p'... not there"
            p=`expr "$p" : '[^-][^-]*-\(.*\)'` > /dev/null
        done
        if [ -z "$p" ]; then
            echo "*** no deployment unit found" && exit 1
        fi

        local t=$(grep '<deployment.target>' deploys/$p/pom.xml|head -1|awk 'BEGIN{FS="[<>]"}{print $3}')
        if [ -z "$t" ]; then
            t=webapps
        fi
        local f=$(find deploys/$p -type f -name '*war' 2>/dev/null)
        if [ -z "$f" ]; then
            echo "*** no deployment unit found" && exit 1
        fi
        echo "Deployment module: $m, prefix: $p, target: $t, file: $f"
        echo "Preparing server '$2' ..."

        ssh ${user:-${USER}}@$2 '$HOME/deployment/rt/bin/deploy_prep' $m $t
        echo "Deploying '$m' to server '$2' ..."
        echo "put $f deployment" | sftp -oBatchMode=yes -b - ${user:-${USER}}@$2 >/dev/null
        ssh ${user:-${USER}}@$2 '$HOME/deployment/rt/bin/deploy_link' $m $t $REV
    else
        echo "Unknown server: $2"
    fi
}

. $(dirname $0)/apply
apply "" "$1" +

