#!/bin/sh

case $# in
1) ;;
*) echo "Usage: $0 { SERVER | @ENV }"; exit 0;;
esac

# project revision to deploy
TOP=$(dirname $0)/..
REV=$(cd $TOP && grep '<global.version>' pom.xml|awk 'BEGIN{FS="[<>]"}{print $3}')
GRP=$(cd $TOP && grep '<groupId>' pom.xml|head -1|awk 'BEGIN{FS="[<>]"}{print $3}'|sed 's/\./\//g')

ctrl() {
    local m
    if m=`expr "$2" : '\(.*[^.0-9]\)[0-9]*\..*'` > /dev/null
    then
        local p=`expr "$m" : '[^-][^-]*-\(.*\)'` > /dev/null
        local t=$(cd $TOP/deploys/$p && grep '<deployment.target>' pom.xml|head -1|awk 'BEGIN{FS="[<>]"}{print $3}')
        if [ -z "$t" ]; then
            t=webapps
        fi
        echo "Preparing server '$2' ..."
        ssh root@$2 '$HOME/deployment/rt/bin/deploy_prep' $m $t
        echo "Deploying '$m' to server '$2' ..."
        echo "put ${M2_REPO:-$HOME/.m2/repository}/$GRP/$m/$REV/$m-$REV.war deployment" | sftp -oBatchMode=yes -b - root@$2 > /dev/null
        ssh root@$2 '$HOME/deployment/rt/bin/deploy_link' $m $t $REV
    else
        echo "Unknown server: $2"
    fi
}

. $(dirname $0)/apply
apply "" "$1" +

