#!/bin/sh

usage() {
  echo Usage: $0 [ --released ] GroupId ArtifactId Module1Name Deployment1Name
}

case $# in
4) mvn archetype:generate -DarchetypeCatalog=local \
    -DarchetypeGroupId=org.xillium \
    -DarchetypeArtifactId=xillium-arch \
    -DarchetypeVersion=1.0-SNAPSHOT \
    -DgroupId=$1 \
    -DartifactId=$2 \
    -Dmodule1name=$3 \
    -Ddeploy1name=$4
   ;;
5) if [ "$1" == "--released" ]
   then
      shift
      mvn archetype:generate -DarchetypeCatalog=local -DarchetypeRepository=https://oss.sonatype.org/content/repositories/snapshots \
        -DarchetypeGroupId=org.xillium \
        -DarchetypeArtifactId=xillium-arch \
        -DarchetypeVersion=1.0-SNAPSHOT \
        -DgroupId=$1 \
        -DartifactId=$2 \
        -Dmodule1name=$3 \
        -Ddeploy1name=$4
   else
      usage; exit 0
   fi
   ;;
*) usage; exit 0
   ;;
esac

