#!/bin/sh

case $# in
1) ;;
*) echo "Usage: $0 @ENV"; exit 0;;
esac

echo -n Checking ssh ...
if type ssh > /dev/null 2>&1
then
    echo found
else
    echo not found
    exit 0
fi

rm -f /tmp/xillium.rt.zip
(cd `dirname $0` && zip -r9 /tmp/xillium.rt.zip rt > /dev/null 2>&1)

ctrl() {
    ssh ${user:-${USER}}@$2 "mkdir -p deployment"
    echo "put /tmp/xillium.rt.zip deployment" | sftp -oBatchMode=yes -b - ${user:-${USER}}@$2 > /dev/null 2>&1
    echo "Installing ..."
    ssh ${user:-${USER}}@$2 "rm -rf deployment/rt && unzip -d deployment deployment/xillium.rt.zip > /dev/null 2>&1"
    echo "Cleaning up ..."
    ssh ${user:-${USER}}@$2 "rm -f deployment/xillium.rt.zip"
    echo "Setting up environment ..."
    ssh ${user:-${USER}}@$2 "chmod +x deployment/rt/bin/* && sh deployment/rt/bin/inst $3"
}

. $(dirname $0)/apply
if expr "$1" : '@.*$' > /dev/null; then
    apply '' $1 -
else
    apply '' @$1 -
fi

rm -f /tmp/xillium.rt.zip
